services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cattle_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=your_secure_password

  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data

  mqtt_worker:
    build: .
    volumes:
      - .:/app
    command: python telemetry/mqtt_consumer.py
    restart: always
    depends_on:
      - db
      - mqtt
    environment:
      - DATABASE_URL=postgres://admin:your_secure_password@db:5432/cattle_db
      - PYTHONUNBUFFERED=1

  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 ktinoskare.asgi:application"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db
      - mqtt
    environment:
      - DATABASE_URL=postgres://admin:your_secure_password@db:5432/cattle_db
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"   # access pgAdmin at http://localhost:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=your_pgadmin_password
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  mosquitto_data:
  pgadmin_data: