# Generated by Django 6.0.3 on 2026-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(max_length=100, unique=True)),
                ('firmware_version', models.CharField(max_length=50)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
