# Generated by Django 6.0.3 on 2026-03-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='breed',
            new_name='breedId',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='owner',
            new_name='ownerId',
        ),
    ]
