# Generated by Django 6.0.3 on 2026-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_breed_pet_breedid_rename_owner_pet_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='healthStatus',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Under Treatment', 'Under Treatment'), ('Recovering', 'Recovering')], default='Healthy', max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='lastCheckup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='nextCheckup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
