# Generated by Django 6.0.3 on 2026-04-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_ip_address_device_is_active_device_name_and_more'),
        ('pets', '0003_pet_age_pet_avatar_pet_color_pet_healthstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet', to='devices.device'),
        ),
    ]
