# Generated by Django 6.0.3 on 2026-04-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='ownerId',
            new_name='owner',
        ),
    ]
