# Generated by Django 6.0.3 on 2026-04-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_rename_ownerid_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
