# Generated by Django 6.0.3 on 2026-04-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetCategory',
            new_name='Species',
        ),
    ]
