# Generated by Django 6.0.3 on 2026-04-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_rename_petcategory_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petbread',
            old_name='category',
            new_name='species',
        ),
    ]
