# Generated by Django 6.0.3 on 2026-04-07 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_rename_category_petbread_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='breedId',
            new_name='breed_id',
        ),
        migrations.RenameField(
            model_name='petbread',
            old_name='species',
            new_name='species_id',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='species',
        ),
        migrations.AddField(
            model_name='pet',
            name='species_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.species'),
        ),
    ]
