# Generated by Django 6.0.3 on 2026-04-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_rename_breedid_pet_breed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petbread',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
