# Generated by Django 6.0.3 on 2026-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_alter_petbread_name_alter_species_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
