# Generated by Django 6.0.3 on 2026-04-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_pet_deleted_at_pet_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='petbread',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petbread',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
