# Generated by Django 6.0.3 on 2026-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('high_temperature', 'High Temperature'), ('low_battery', 'Low Battery'), ('abnormal_heart_rate', 'Abnormal Heart Rate'), ('geofence_breach', 'Geofence Breach')], max_length=50, null=True),
        ),
    ]
