# Generated by Django 6.0.3 on 2026-03-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('', 'None'), ('high_temperature', 'High Temperature'), ('low_battery', 'Low Battery'), ('abnormal_heart_rate', 'Abnormal Heart Rate'), ('geofence_breach', 'Geofence Breach')], default='', max_length=50),
        ),
    ]
