# Generated by Django 6.0.3 on 2026-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('high_temperature', 'High Temperature'), ('low_battery', 'Low Battery'), ('abnormal_heart_rate', 'Abnormal Heart Rate'), ('geofence_breach', 'Geofence Breach')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
