# Generated by Django 6.0.3 on 2026-05-31 08:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('window_seconds', models.IntegerField(default=30)),
                ('avg_heart_rate', models.FloatField(blank=True, null=True)),
                ('min_heart_rate', models.FloatField(blank=True, null=True)),
                ('max_heart_rate', models.FloatField(blank=True, null=True)),
                ('avg_spo2', models.FloatField(blank=True, null=True)),
                ('min_spo2', models.FloatField(blank=True, null=True)),
                ('max_spo2', models.FloatField(blank=True, null=True)),
                ('avg_ambient_temp', models.FloatField(blank=True, null=True)),
                ('avg_object_temp', models.FloatField(blank=True, null=True)),
                ('max_object_temp', models.FloatField(blank=True, null=True)),
                ('accel_x', models.FloatField(blank=True, null=True)),
                ('accel_y', models.FloatField(blank=True, null=True)),
                ('accel_z', models.FloatField(blank=True, null=True)),
                ('motion_detected', models.BooleanField(default=False)),
                ('light_level', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('battery_percentage', models.IntegerField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('temp_dht22', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('heat_index', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device')),
            ],
            options={
                'db_table': 'telemetry_telemetryrecord',
                'ordering': ['-created_at'],
            },
        ),
        # --- RESTORED SPATIAL-TEMPORAL COMPOSITE KEY TRANSFORMATION ---
        migrations.RunSQL(
            sql=[
                # 1. Drop standard single constraint
                "ALTER TABLE telemetry_telemetryrecord DROP CONSTRAINT telemetry_telemetryrecord_pkey;",
                # 2. Bind composite key (id + partitioning time column axis)
                "ALTER TABLE telemetry_telemetryrecord ADD PRIMARY KEY (id, created_at);",
                # 3. Securely turn the table into an optimized TimescaleDB hypertable
                "SELECT create_hypertable('telemetry_telemetryrecord', 'created_at', if_not_exists => TRUE);"
            ],
            reverse_sql="-- Cannot reverse cleanly"
        ),
    ]
