# Generated by Django 6.0.3 on 2026-03-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_telemetryrecord_motion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemetryrecord',
            old_name='temperature',
            new_name='ambient_temperature',
        ),
        migrations.RenameField(
            model_name='telemetryrecord',
            old_name='battery_level',
            new_name='battery_voltage',
        ),
        migrations.RemoveField(
            model_name='telemetryrecord',
            name='motion',
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='accel_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='accel_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='accel_z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='battery_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='light_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='motion_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='object_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='spo2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
