# Generated by Django 6.0.3 on 2026-03-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_rename_temperature_telemetryrecord_ambient_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetryrecord',
            name='latitude',
            field=models.CharField(default='0.0', max_length=25),
        ),
        migrations.AlterField(
            model_name='telemetryrecord',
            name='longitude',
            field=models.CharField(default='0.0', max_length=25),
        ),
    ]
