# Generated by Django 6.0.3 on 2026-03-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_alter_telemetryrecord_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemetryrecord',
            old_name='ambient_temperature',
            new_name='avg_ambient_temp',
        ),
        migrations.RenameField(
            model_name='telemetryrecord',
            old_name='heart_rate',
            new_name='avg_heart_rate',
        ),
        migrations.RenameField(
            model_name='telemetryrecord',
            old_name='object_temperature',
            new_name='avg_object_temp',
        ),
        migrations.RenameField(
            model_name='telemetryrecord',
            old_name='spo2',
            new_name='avg_spo2',
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='max_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='max_object_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='max_spo2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='min_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='min_spo2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='window_seconds',
            field=models.IntegerField(default=30),
        ),
    ]
