# Generated by Django 6.0.3 on 2026-04-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_rename_ambient_temperature_telemetryrecord_avg_ambient_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetryrecord',
            name='heat_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telemetryrecord',
            name='temp_dht22',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
